# This workflow will install Python dependencies, run tests and lint with a single version of Python
# For more information see: https://help.github.com/actions/language-and-framework-guides/using-python-with-github-actions

name: On release

on:
  push:
    branches: [ master ]

jobs:
  pypi-publish:
    runs-on: 'ubuntu-latest'
    environment:
      name: pypi
      url: https://pypi.org/p/instruct
    permissions:
      id-token: write
    steps:
      - 
        uses: actions/checkout@v4
      - 
        name: Set up Python 3.11
        uses: actions/setup-python@v4
        with:
          python-version: '3.11'
          architecture: 'x64'
      - 
        name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          python -m pip install -r dev-requirements.txt
      - 
        name: Create artifacts
        run: |
          python -m build
      - 
        name: Publish package distributions to PyPI
        uses: pypa/gh-action-pypi-publish@release/v1

    

