# This workflow will install Python dependencies, run tests and lint with a single version of Python
# For more information see: https://help.github.com/actions/language-and-framework-guides/using-python-with-github-actions

name: Check style

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:
    strategy:
      fail-fast: false
      matrix:
        arch:
          - 'x64'
        python_version:
          - '3.x'
        os: 
          - 'ubuntu-latest'
    runs-on: ${{ matrix.os }}
    steps:
      - 
        uses: actions/checkout@v4
      - 
        name: Set up Python ${{ matrix.python_version }}
        uses: actions/setup-python@v4
        with:
          python-version: ${{ matrix.python_version }}
          architecture: ${{ matrix.arch }}
      - 
        name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          python -m pip install black==19.3b0 click==8.0.1 
          python -m pip install .[devel,test]
      - 
        name: Lint with flake8
        run: |
          # stop the build if there are Python syntax errors or undefined names
          python -m flake8 instruct/ --count --select=E9,F63,F7,F82 --show-source --statistics
          # exit-zero treats all errors as warnings. The GitHub editor is 127 chars wide
          python -m flake8 instruct/ --count --exit-zero --max-complexity=10 --max-line-length=127 --statistics
      - 
        name: Check style
        run: |
          python -m black --check

    

