# This workflow will install Python dependencies, run tests and lint with a single version of Python
# For more information see: https://help.github.com/actions/language-and-framework-guides/using-python-with-github-actions

name: Tests

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:
    strategy:
      fail-fast: false
      matrix:
        arch:
          - 'x64'
        python_version:
          - '3.7'
          - '3.8'
          - '3.9'
          - '3.10'
          - '3.11'
          - '3.12'
        os: 
          - 'ubuntu-latest'
    runs-on: ${{ matrix.os }}
    steps:
      - 
        uses: actions/checkout@v4
      - 
        name: Set up Python ${{ matrix.python_version }}
        uses: actions/setup-python@v4
        with:
          python-version: ${{ matrix.python_version }}
          architecture: ${{ matrix.arch }}
      - 
        name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          mkdir wheels
          python -m pip wheel -w wheels -r setup-requirements.txt -r dev-requirements.txt -r test-requirements.txt
          python -m pip install --no-index --find-links=wheels/ build
          python -m build
          python -m pip install --find-links=dist/ --find-links=wheels/ --no-index instruct[devel,test]
      - 
        name: Test with pytest
        run: |
          python -m pytest
